-- Create rin_gtm_drafts table with same schema as gtm_drafts
CREATE TABLE IF NOT EXISTS public.rin_gtm_drafts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  draft_date DATE NOT NULL,
  draft_type VARCHAR(255),
  channel VARCHAR(255),
  title TEXT,
  content TEXT,
  status VARCHAR(50) DEFAULT 'draft',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(draft_date)
);

-- Create index on draft_date for faster queries
CREATE INDEX IF NOT EXISTS idx_rin_gtm_drafts_date ON public.rin_gtm_drafts(draft_date);

-- Set up RLS policies (same as gtm_drafts if needed)
ALTER TABLE public.rin_gtm_drafts ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rin_gtm_drafts TO anon, authenticated;

-- Verify table exists
SELECT * FROM information_schema.tables WHERE table_name = 'rin_gtm_drafts';
